name: 'LeetCode Markdown Generation'
description: 'Generates markdown files for LeetCode submissions in my-submissions folder'

runs:
  using: 'composite'
  main: '.github/workflows/generate-markdowns.yml'


# name: '[Updating markdown files]'

# on:
#     # If you want it to run max once a day
#     # schedule:
#     # - cron: "25 8 * * *"    #runs at 12am PST each day


#     # Allows for manual runs
#     workflow_call:
#         secrets:
#             PAT:
#               required: true

